// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eetRVbLy8gp7SoVBTaw9Ti
// Component: 5O0QXTXkg3T
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: DCbVgJMF2s3/component
import ProductCarousel from "../../ProductCarousel"; // plasmic-import: sJAucJnH9brm/component
import ProductCard from "../../ProductCard"; // plasmic-import: DLx69AOkXu3Q/component
import Ratings from "../../Ratings"; // plasmic-import: 33vX5qOZnwG2/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: 7H-u0N_tYUf/component
import BlogPost from "../../BlogPost"; // plasmic-import: XzmLEFuAeCIB/component
import Footer from "../../Footer"; // plasmic-import: FoSHlSKaK_5/component
import { useScreenVariants as useScreenVariantscsw71UGhxUHg } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: CSW71UGhxUHg/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: eetRVbLy8gp7SoVBTaw9Ti/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: 5O0QXTXkg3T/css

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantscsw71UGhxUHg()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__xbqEn)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__wGsUi)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___2Zia2)}>
                <Header
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                />

                <ProductCarousel
                  data-plasmic-name={"productCarousel"}
                  data-plasmic-override={overrides.productCarousel}
                  className={classNames("__wab_instance", sty.productCarousel)}
                />
              </div>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox___8LFwZ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gbWW
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__hJlum)}
            >
              <div className={classNames(projectcss.all, sty.column__wpAr)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__qje4W
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__na42E)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals1.png",
                        fullWidth: 120,
                        fullHeight: 120,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___9OuCs
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column___2M4HX)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wOyZo
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__lXq6W)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals2.png",
                        fullWidth: 138,
                        fullHeight: 116,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__lQnBr
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Single Armchair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__zi2P0)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__pFtP
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__riZoL)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals3.png",
                        fullWidth: 135,
                        fullHeight: 116,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__iQo8
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Armchair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__qh7Lp)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vHeor
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__wErZf)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals4.png",
                        fullWidth: 100,
                        fullHeight: 130,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__d6OyK
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Stylish Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__uThWt)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__khMeG
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__td0Me)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals5.png",
                        fullWidth: 105,
                        fullHeight: 127,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$120.00"}
                  title={"Modern Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__hbWQ)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gTqCq
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___45E)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals6.png",
                        fullWidth: 176,
                        fullHeight: 123,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$140.00"}
                  title={"Mapple Wood Dinning Table"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__lfhT1)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fJey7
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__twcVv)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals7.png",
                        fullWidth: 160,
                        fullHeight: 120,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$90.00"}
                  title={"Arm Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__rldXr)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__i4Uko
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hlLfn)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals8.png",
                        fullWidth: 191,
                        fullHeight: 101,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$140.00"}
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ieGr
                      )}
                    >
                      {"Wooden Bed"}
                    </div>
                  }
                />
              </div>
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__lAsWs)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fcfQt
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__j3Jp7)}
            >
              <div className={classNames(projectcss.all, sty.column__hu2Jw)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___6ZOu
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xVfxH
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__wbqdv
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vFkPh
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={"withReviews"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__ndzqN)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__eAEkg
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__vg7R4)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/f2.jpeg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___6XO7
                      )}
                      stars={"four"}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={"withReviews"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__nWgBb)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tI3Sl
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__qWpTu)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/f3.jpeg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__jVpT
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five"}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={"withReviews"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column___518Ql)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wHjv
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tA1Iv)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/f4.jpeg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__d5Kl6
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={"withReviews"}
                />
              </div>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox___5SR77)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8NfMx
                )}
              >
                {"Latest BlasaS"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ia9F)}
            >
              <div className={classNames(projectcss.all, sty.column__zfeeA)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost___7StuC)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__dz2Mb)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/b1.jpeg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__zo7CZ)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__ql3Ji)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__b77QY)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/b2.jpeg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__qZztZ)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__x7QhI)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___8LLmM)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/b3.jpeg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__wLgY)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__cA9Rc)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: "/plasmic/furn_e_commerce/images/adidas.png",
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__xm6C0)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: "/plasmic/furn_e_commerce/images/hm.png",
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__r7S5I)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: "/plasmic/furn_e_commerce/images/kappa.png",
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__yNlVw)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: "/plasmic/furn_e_commerce/images/lacoste.png",
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__bCV3)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: "/plasmic/furn_e_commerce/images/levis.png",
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
