// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eetRVbLy8gp7SoVBTaw9Ti
// Component: 33vX5qOZnwG2
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: eetRVbLy8gp7SoVBTaw9Ti/projectcss
import * as sty from "./PlasmicRatings.module.css"; // plasmic-import: 33vX5qOZnwG2/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: VyIngv8mxeG-/icon

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

function PlasmicRatings__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root, {
        [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
        [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
        [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
        [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
        [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
        [sty.root__stars_zero]: hasVariant(variants, "stars", "zero")
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__c8X4, {
              [sty.svg__stars_five__c8X4MbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_zero__c8X48R6Yg]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___5HTr9, {
              [sty.svg__stars_five___5HTr9MbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four___5HTr9G6Rj6]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one___5HTr9Cr4Zd]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three___5HTr9VsLwm]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two___5HTr99Zuto]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero___5HTr98R6Yg]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__czA1E, {
              [sty.svg__stars_five__czA1EMbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__czA1Eg6Rj6]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__czA1Ecr4Zd]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__czA1EVsLwm]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__czA1E9Zuto]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__czA1E8R6Yg]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__jIp4T, {
              [sty.svg__stars_five__jIp4TMbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__jIp4TG6Rj6]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__jIp4Tcr4Zd]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__jIp4TVsLwm]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__jIp4T9Zuto]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__jIp4T8R6Yg]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___9FxIt, {
              [sty.svg__stars_five___9FxItMbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four___9FxItG6Rj6]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one___9FxItcr4Zd]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three___9FxItVsLwm]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two___9FxIt9Zuto]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero___9FxIt8R6Yg]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__i44Yh, {
              [sty.svg__stars_five__i44YhMbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__i44YhG6Rj6]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__i44Yhcr4Zd]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__i44YhVsLwm]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__i44Yh9Zuto]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__i44Yh8R6Yg]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__alYi3, {
              [sty.svg__stars_five__alYi3MbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__alYi3G6Rj6]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_three__alYi3VsLwm]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__alYi39Zuto]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___6Ody, {
              [sty.svg__stars_five___6OdyMbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four___6OdyG6Rj6]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_three___6OdyVsLwm]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__sAsH0, {
              [sty.svg__stars_five__sAsH0MbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__sAsH0G6Rj6]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__edYH, {
              [sty.svg__stars_five__edYHMbUpw]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
